Pin grpcio-tools
grpcio-tools >= 1.62 breaks our build. See issue https://github.com/IRL2/nanover-protocol/issues/43

diff --git a/.github/workflows/conda.yml b/.github/workflows/conda.yml
--- a/.github/workflows/conda.yml
+++ b/.github/workflows/conda.yml
@@ -29,7 +29,7 @@ jobs:
         run: bash ./maintainers/check_extra_init_files.sh
       - name: Install dependencies
         # We temporarilly ignore failure here. See #31.
-        run: conda install -y python conda-build grpcio-tools conda-verify || echo "Fail?"
+        run: conda install -y python conda-build "grpcio-tools<1.62" conda-verify || echo "Fail?"
       - name: Compiling the prototypes
         run: python python-libraries/nanover-core/setup.py compile_proto --proto-dir=protocol
       - name: Building the Conda packages
