Temporary fix for failing CI
The CI fails systematically when installing packages using conda. The
install goes through but ends with an exit code of 1 indicating failure.
This commit ignores the failure as a temporary workaround.

See #31.

diff --git a/.github/workflows/conda.yml b/.github/workflows/conda.yml
--- a/.github/workflows/conda.yml
+++ b/.github/workflows/conda.yml
@@ -28,7 +28,8 @@ jobs:
       - name: Test that the repo is sane and does not contain superfluous __init__ file
         run: bash ./maintainers/check_extra_init_files.sh
       - name: Install dependencies
-        run: conda install python conda-build grpcio-tools conda-verify
+        # We temporarilly ignore failure here. See #31.
+        run: conda install -y python conda-build grpcio-tools conda-verify || echo "Fail?"
       - name: Compiling the prototypes
         run: python python-libraries/narupa-core/setup.py compile_proto --proto-dir=protocol
       - name: Building the Conda packages
@@ -73,7 +74,8 @@ jobs:
         with:
           name: conda-packages
       - name: Install Narupa
-        run: conda install -c conda-forge -c ./conda-bld mpi4py narupa-server narupa-lammps
+        # We temporarilly ignore failure here. See #31.
+        run: conda install -y -c conda-forge -c ./conda-bld mpi4py narupa-server narupa-lammps || echo "Fail?"
       - name: Install tests dependancies
         run: python -m pip install -r python-libraries/requirements.test
       - name: Parallel tests
@@ -105,7 +107,8 @@ jobs:
         with:
           name: conda-packages
       - name: Install Anaconda
-        run: conda install anaconda-client
+        # We temporarilly ignore failure here. See #31.
+        run: conda install -y anaconda-client || echo "Fail?"
       - name: Connect to Anaconda cloud
         # The login token may be used by a failed build already. If we are asked
         # if we want it back, we say yes. Hence the echo Y.
