Upload conda packages

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -78,6 +78,43 @@ jobs:
         run: python -m pytest --cov narupa python-libraries -n auto -m 'not serial'
       - name: Serial tests
         run: python -m pytest --cov narupa python-libraries -n auto -m 'serial'
+  publish-conda:
+    name: Publish the conda packages on Anaconda cloud
+    runs-on: ubuntu-latest
+    needs: test-conda
+    defaults:
+      run:
+        # This is necessary for the conda action. It replaces `conda init` as
+        # the shell does not load ,profile or .bashrc.
+        shell: bash -el {0}
+    if: github.ref == 'refs/heads/build-conda'
+    steps:
+      - uses: actions/checkout@v3
+      - uses: conda-incubator/setup-miniconda@v2
+        with:
+          auto-update-conda: true
+          # WARNING! On the contrary to all the other places where we install
+          # conda, we install miniconda and NOT miniforge!
+          # This is because we do not need packages to RUN narupa, but packages
+          # from the default (anaconda) channel to upload to anaconda.
+          miniconda-version: latest
+      - name: Retrieve conda packages
+        uses: actions/download-artifact@v3
+        with:
+          name: conda-packages
+      - name: Install Anaconda
+        run: conda install anaconda-client
+      - name: Connect to Anaconda cloud
+        # The login token may be used by a failed build already. If we are asked
+        # if we want it back, we say yes. Hence the echo Y.
+        run: echo Y | anaconda login --username irl_bot --password ${{ secrets.ANACONDA_PASSWORD }}
+      - name: Upload packages
+        # Anaconda will complain if the given version of a package is already
+        # there. Until we have some versioning, we force the upload.
+        run: anaconda  upload --user irl conda-bld/noarch/narupa-*.tar.bz2 --force
+      - name: Disconnect from Anaconda cloud
+        #  Do not fail the build if we cannot logout.
+        run: anaconda logout || echo "Could not logout. Too bad."
   python-tests:
     name: Python unit and integration tests
     runs-on: ubuntu-latest
